name: Distribution Builds

on:
  pull_request:
    types:
      - closed
  # Manual dispatch for testing
  workflow_dispatch:

jobs:
  build:
    env:
      ITCH_PROJECT: 'sandramoen/chaingun-command'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: jdno/setup-butler@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build core
        run: ./gradlew core:assemble
      - name: Build html
        run: ./gradlew html:dist
      - name: Artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: html/build/dist
          retention-days: 1
      - name: Deploy 🚀
        run: butler push html/build/dist $ITCH_PROJECT:html
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
